<?php

/**
 * @file
 * Contains listener.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function listener_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the listener module.
    case 'help.page.listener':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */

function listener_theme()
{
  $theme = [];
    $theme['post'] = array(
        'render element' => 'elements',
        'file' => 'post.page.inc',
        'template' => 'post',
    );

  return $theme;
}
