config_packager.export:
  path: '/admin/config/development/configuration/packager'
  defaults:
    _form: '\Drupal\config_packager\Form\ConfigPackagerExportForm'
    _title: 'Export'
  requirements:
    _permission: 'export configuration'

config_packager.export_download:
  path: '/admin/config/development/configuration/packager/export-download'
  defaults:
    _controller: '\Drupal\config_packager\Controller\ConfigPackagerController::downloadExport'
  requirements:
    _permission: 'export configuration'

config_packager.assignment:
  path: '/admin/config/development/configuration/packager/assignment'
  defaults:
    _form: '\Drupal\config_packager\Form\AssignmentConfigureForm'
    _title: 'Assignment'
  requirements:
    _permission: 'administer site configuration'

config_packager.assignment_base:
  path: '/admin/config/development/configuration/packager/assignment/base'
  defaults:
    _form: '\Drupal\config_packager\Form\AssignmentBaseForm'
    _title: 'Configure base package assignment'
  requirements:
    _permission: 'administer site configuration'

config_packager.assignment_core:
  path: '/admin/config/development/configuration/packager/assignment/core'
  defaults:
    _form: '\Drupal\config_packager\Form\AssignmentCoreForm'
    _title: 'Configure core package assignment'
  requirements:
    _permission: 'administer site configuration'

config_packager.assignment_exclude:
  path: '/admin/config/development/configuration/packager/assignment/exclude'
  defaults:
    _form: '\Drupal\config_packager\Form\AssignmentExcludeForm'
    _title: 'Configure package exclusion'
  requirements:
    _permission: 'administer site configuration'
